#
# arxiv-pdftotex cloudbuild.yaml
# This cloudbuild is used for PR testing and is run on each push
# to the repo
version: '3'
services:
  dind-service:
    image: docker:27.3.1-dind
    privileged: true
    ports:
      - "127.0.0.1:2375:2375"
      - "127.0.0.1:2376:2376"
networks:
  default:
    external:
      name: cloudbuild
steps:
  # Step 0: start the docker in docker service
  - id: start-dind
    name: docker/compose
    args: ['-f', 'docker-compose.yml', 'up', '-d', 'dind-service']

  - id: 'Check service is listening'
    name: gcr.io/cloud-builders/curl
    args: ["dind-service:2375"]
    waitFor: [start-dind]

  - name: 'ghcr.io/astral-sh/uv:python3.12'
    waitFor: [start-dind]
    id: run-pytest
    entrypoint: 'bash'
    env:
      - 'DOCKER_HOST=tcp://dind-service:2375'
    args:
      - '-c'
      - |
        set -e
        pytest tests

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

substitutions:
  _IMAGE_NAME: "arxiv-pdftotext"
