steps:
  # Step 1: Build the Docker image with commit hash
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'DOCKER_BUILDKIT=1 docker build -t gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA} .'

 # Step 2: Tag the same image as 'dev'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag',
           'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}',
           'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG}'
          ]

  # Step 3: Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG}']

  # Step 4: Deploy to production Cloud Run
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args:
#    - 'run'
#    - 'deploy'
#    - 'arxiv-pdftotext'
#    - '--service-account'
#    - 'qa-tools-sa@${PROJECT_ID}.iam.gserviceaccount.com'
#    - '--min-instances=default'
#    - '--timeout=300'
#    - '--image'
#    - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG}'
#    - '--region'
#    - 'us-central1'
#    - '--platform'
#    - 'managed'
#    - '--port'
#    - '8888'

images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

# create TAG dev / prod from PROJECT_ID via substitutions
substitutions:
  _IMAGE_NAME: "arxiv-pdftotext"
  _ENVIRONMENT: ${PROJECT_ID/arxiv-}
  _TAG_PRE1: ${_ENVIRONMENT/uction}
  _TAG: ${_TAG_PRE1/elopment}
