steps:
  # Step 1: Build the Docker image with commit hash
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}', '.'
          ]

  # Step 2: Tag the same image as 'dev'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag',
           'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}',
           'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:dev'
          ]

  # Step 3: Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:dev']

images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:dev'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

substitutions:
  _IMAGE_NAME: "arxiv-pdftotext"