[project]
name = "arxiv-pdftotext"
version = "0.1.0"
description = "pdftotext and pdf2txt. As a webservice, containerized!"
readme = "README.md"
requires-python = ">3.12, <3.14"
dependencies = [
    "fastapi",
    "google-cloud-storage",
    "hypercorn",
    "pdfminer-six",
    "pydantic-settings>=2.13.1",
    "python-multipart",
]

[dependency-groups]
dev = [
    "ruff",
    "pytest",
    "requests",
    "pre-commit",
    "ty",
    "httpx>=0.28.1",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle errors
    "PLC",
    "PLE",
    "PLW", # Pylint
    "RUF", # ruff internal check
]

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
