steps:
  # Step 1: Build the Docker image with commit hash
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'DOCKER_BUILDKIT=1 docker build -t gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA} .'

  # Step 2: Tag the same image as 'dev'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag',
           'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}',
           'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:dev'
          ]

  # Step 3: Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:dev']

  # Step 4: Deploy to production Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'arxiv-pdftotext'
    - '--service-account'
    - 'qa-tools-sa@arxiv-development.iam.gserviceaccount.com'
    - '--min-instances=default'
    - '--timeout=300'
    - '--image'
    - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${TAG_NAME}'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--port'
    - '8888'

images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:dev'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

substitutions:
  _IMAGE_NAME: "arxiv-pdftotext"
