name: Deploy

run-name: "Deploy qa-pdftotext ${{ inputs.environment }}"

on:
  workflow_call:
    inputs:
      image_name:
        description: Image name
        required: false
        type: string
      environment:
        description: Environment (dev or prod)
        required: true
        type: string
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Commit SHA to deploy (leave blank for latest)
        required: false
        type: string
      image_name:
        description: Image name
        required: false
        type: string
      environment:
        description: Environment (dev or prod)
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  COMMIT_SHA: ${{ inputs.commit_sha || github.sha }}
  IMAGE_URI: gcr.io/arxiv-development/${{ inputs.image_name }}:${{ inputs.commit_sha || github.sha }}

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check version
        run: terraform --version

      - name: Format check
        run: terraform fmt terraform/ terraform/envs/

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set environment
        run: |
          if [[ "${{ inputs.environment }}" == "prod" ]]; then
            echo "PROVIDER_NAME=${{ vars.ARXIV_PRODUCTION_PROVIDER_NAME }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=${{ vars.ARXIV_PRODUCTION_SERVICE_ACCOUNT }}" >> $GITHUB_ENV
            echo "ENV_VAR=prod" >> $GITHUB_ENV
          elif [[ "${{ inputs.environment }}" == "dev" ]]; then
            # Default to Development
            echo "PROVIDER_NAME=${{ vars.ARXIV_DEVELOPMENT_PROVIDER_NAME }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=${{ vars.ARXIV_DEVELOPMENT_SERVICE_ACCOUNT }}" >> $GITHUB_ENV
            echo "ENV_VAR=dev" >> $GITHUB_ENV
          else
            echo "Invalid environment!"
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.PROVIDER_NAME }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v4

      - name: Check version
        run: terraform --version

      - name: Initialize remote backend
        run: terraform init -backend-config="bucket=${{ env.ENV_VAR }}-arxiv-terraform-state"
        working-directory: terraform

      - name: Format check
        run: terraform fmt -check
        working-directory: terraform

      - name: Apply
        run: terraform apply -var-file=envs/${{ env.ENV_VAR }}.tfvars -var="image_path=${{ env.IMAGE_URI }}" -auto-approve
        working-directory: terraform
