name: pdftotext triggers

on:
  push:
    branches:
      - master
      - development
    paths:
      - "webserver.py"
      - "Dockerfile"
      - "terraform/**"
      - "run-me.sh"
  pull_request:
    branches:
      - master
      - development
    paths:
      - "webserver.py"
      - "Dockerfile"
      - "terraform/**"
      - "run-me.sh"
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint-test:
    name: Lint qa-pdftotext
    uses: ./.github/workflows/lint-test.yml

  call-build-push:
    needs: call-lint-test
    name: Build push qa-pdftotext
    uses: ./.github/workflows/build-push.yml
    with:
      image_name: qa-pdftotext

  call-deploy-dev:
    needs: [ call-lint-test, call-build-push ]
    # deploy latest commit to dev automatically if merged to master
    if: github.ref == 'refs/heads/master'
    name: Deploy qa-pdftotext
    uses: ./.github/workflows/deploy.yml
    with:
      image_name: qa-pdftotext
      environment: dev
